### ISSUE TITLE
todo for frontend

### ISSUE THREAD

**Issue by Raj6939** [hypersign-protocol/studio#118]
- [x] Profile icon color change and add email, did and logout `icon` in three rows
- [x] remove the organization from create org sidebar and keep it Name only
- [x] add dashboard scrollbar
- [x] add issuer did field while creating a credential
- [x] add icons in the dashboard on horizontal cards (ex schema count card)
