### ISSUE TITLE
TODO list 

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/studio#20]
- [ ] Add/Edit Orgnaization slider does not get refresh on clicking `+ Organization` button if we already clicked on  `Edit` button in the org card.
- [ ] `Add Orgnaization` header comes in the slider when clicking on edit button in org card. It should be `Edit Organization`
- [ ] The entire screen shakes when typing something in slider text boxes in some screen. Try different screen size. 
- [ ] Add fontawesomes package to make use of icons 

## Schema
- [ ] Clicking on `Transaction Hash` link on schema row, redirecting to wrong url.

## VC
- [ ] VC Id URL -  it should be an ID instead.
- [ ]

**Comment by Vishwas1** [comment]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/15328561/193499668-741dfe1e-0a62-46d6-a6b0-276d634d68f2.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/15328561/193500544-8456ca2c-7f1e-4495-a913-dda38bd9c3e0.png">
